// Todos os distritos de Portugal Continental + Ilhas
export const ESTILOS_DANCA = [
  'Breaking',
  'Popping',
  'Locking',
  'House',
  'Waacking',
  'Voguing',
  'Krump',
  'Hip-Hop',
  'Dancehall',
  'Top Styles',
  'All Styles',
];

export const DISTRITOS_PORTUGAL = [
  'Aveiro',
  'Beja',
  'Braga',
  'Bragança',
  'Castelo Branco',
  'Coimbra',
  'Évora',
  'Faro',
  'Guarda',
  'Leiria',
  'Lisboa',
  'Portalegre',
  'Porto',
  'Santarém',
  'Setúbal',
  'Viana do Castelo',
  'Vila Real',
  'Viseu',
  'Açores',
  'Madeira',
];